name = "welllocks"
main = "_worker.js"
compatibility_date = "2025-08-12"

[assets]
directory = "./static"
binding = "ASSETS"

[vars]
SITE_NAME = "WellLock"
RECIPIENT_EMAIL = "zhejiangrato@gmail.com"

[observability]
enabled = true
